### ISSUE TITLE
Dark subtext on dark backgrounds can be difficult to read

### ISSUE THREAD

**Issue by pyamsoft** [Stevanus/stevan.us#1]
The subtext in the Hero Image and Notes is very dark and can be hard on the eyes in its default color pallete. Perhaps a lighter gray?

Google Material Guidelines
http://www.google.com/design/spec/style/color.html

**Comment by pyamsoft** [comment]
Similarly, the blog text for the posts as well as the objective statement in the resume blend in with respect to their lighter backgrounds.

**Comment by Stevanus** [comment]
Got ya! Thx pyamsoft :)
